name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      working-directory: vite-project
      run: |
        yarn install
        yarn build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        target_branch: gh-pages
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
