name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        pwd
        npm install
        npm run build
      working-directory: vite-project
    - name: ecno
      run: echo ${{ GITHUB_WORKSPACE }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      run: |
        pwd
        echo 'publish'
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: vite-project/dist
